server:
  port: ${server.port}
  tomcat:
    basedir: ${data.path}/tomcat/service

jasypt:
  encryptor:
    password: bdp

auth:
  token:
    api: ENC(doiaIecpZ6QpeVvqcayuWuuWC1C5Nf1V)

spring:
  messages:
    basename: messages
  application:
    name: exchangis-service
  datasource:
    password: ${DB_PASSWORD:pass}
    username: ${DB_USERNAME:udes_ps_bdp}
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_DATABASE:exchangis}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filter:
        config:
            enabled: false
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
  quartz:
      properties:
        org:
          quartz:
            scheduler:
              instanceName: clusteredScheduler
              instanceId: AUTO
            jobStore:
              class: org.quartz.impl.jdbcjobstore.JobStoreTX
              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
              tablePrefix: EXCHANGIS_QRTZ_
              isClustered: true
              clusterCheckinInterval: 10000
              useProperties: false
              acquireTriggersWithinLock: true
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true
      job-store-type: jdbc
      jdbc:
        initialize-schema: NEVER
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  http:
    converters:
      support-json-medias: text/json


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.webank.wedatasphere.exchangis

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}
    fetch-registry: true
    registry-fetch-interval-seconds: 8


# ribbon configuration
ribbon:
  eager-load:
    enabled: true


snowflake:
  startTime: ${SNOWFLAKE_START_TIME}
  workerId: ${SNOWFLAKE_WORKER_ID}
  dataCenterId: ${SNOWFLAKE_DATA_CENTER_ID}
